resources:
  - deployment.yml
  - service.yml

labels:
  - pairs:
      app: webapp
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  app: webapp-annotations

nameSuffix: -v1

